# Generated by Django 4.2.20 on 2025-04-26 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MenuItems', '0001_initial'),
        ('OrderItems', '0002_alter_orderitem_menu_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='menu_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_item', to='MenuItems.menuitem'),
        ),
    ]
