# Generated by Django 4.2.20 on 2025-05-11 06:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('OrderItems', '0001_initial'),
        ('MenuItems', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('items', models.ManyToManyField(related_name='orders', through='OrderItems.OrderItem', to='MenuItems.menuitem')),
            ],
        ),
    ]
