# Generated by Django 4.2.20 on 2025-04-25 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrderItems', '0002_alter_orderitem_menu_item'),
        ('MenuItems', '0001_initial'),
        ('Orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(related_name='orders', through='OrderItems.OrderItem', to='MenuItems.menuitem'),
        ),
    ]
